### ISSUE TITLE
ppl review

### ISSUE THREAD

**Issue by jyp-on** [woorifisa-service-dev-3rd/frontend-1st-Number_Baseball#11]
UX적인 측면에서 생각해보면 숫자를 다 입력해서 바로 제출이 아닌 제출 버튼을 만들면 좋을 것 같습니다.
Log쪽 설명이 직관적이지 않은 것 같습니다. 좀더 이해하기 쉬우면 좋겠어요.

**Comment by bangsk2** [comment]
피드백 주신 내용을 바탕으로 앞으로 수정하며 적극적으로 고려해보겠습니다! 피드백 감사합니다.
