### ISSUE TITLE
키 입력 관련 문의

### ISSUE THREAD

**Issue by kimchang0** [woorifisa-service-dev-3rd/frontend-1st-Number_Baseball#12]
키를 입력해보니 숫자 말고 다른 키도 입력되어서 추후에 JS로 구현하실 때는 숫자 외에는 입력되지 않도록 구현하면 좋을 것 같습니다.

**Comment by bangsk2** [comment]
추후 수정에서 반영하도록 하겠습니다! 피드백 감사합니다!
