### ISSUE TITLE
[강김길] 야구 게임 잘 봤습니다 ! 

### ISSUE THREAD

**Issue by rlfrkdms1** [woorifisa-service-dev-3rd/frontend-1st-Number_Baseball#14]
정말 잘 봤습니다. hover나 애니메이션이 특히 인상적인 것 같습니다. 아래 두가지 의견 드리겠습니다 !

- 네개의 숫자를 입력하고 제출하기 버튼이 없이 모두 입력하면 바로 제출되는 것을 의도하셨다고 했는데, 그러면 마지막 숫자를 잘못 입력했을 때 잘못 제출되는 일이 발생할 것 같습니다. 
- README 에 `Light house 측정결과`, `font`, `color` 사진이 깨져있는데 확인해보시면 좋을 것 같습니다 !

**Comment by bangsk2** [comment]
read me 수정은 완료하였습니다!

피드백 내용을 바탕으로 숫자 입력 방법을 수정하는 방안을 반영해보도록 하겠습니다!
