### ISSUE TITLE
smile team review

### ISSUE THREAD

**Issue by bw02184** [woorifisa-service-dev-3rd/frontend-1st-Number_Baseball#15]
1. readme 사진 깨진 부분 보완하시면 좋을 듯 합니다! 게임 기대됩니다~
2. 제목부분을 클릭해서 새로고침이 되도록 하면좋을 것 같습니다.
3. 킹받는 애니메이션 + UI가 너무 매력적이에요 더 플래시 게임 느낌으로 가도 좋을 것 같아요 (고향만두 플래시 게임 느낌!) 그리고 숫자를 직접 입력할 때 옆칸으로 바로 갈 수 있도록 autofocus 속성 활용을 적극 추천합니다!

**Comment by bangsk2** [comment]
1. read me 반영 완료하였습니다!
2. 헤더부분을 사용하여 해당 피드백을 반영할 수 있도록 해보겠습니다.
3. 킹 받는 컨셉을 유지할 수 있도록 노력하겠습니다! 의견 주신 부분은 반영하도록 노력하겠습니다!
