### ISSUE TITLE
질문있습니다 ✋  

### ISSUE THREAD

**Issue by khwoowoo** [woorifisa-service-dev-3rd/frontend-1st-Number_Baseball#16]
1. 점수기준을 만들어서 랭킹 시스템 있으면 더 재미있게 할 수 있을 것 같은데 혹시 추가하실 의향이 있나요?!
2. 버튼 스타일에 커서 cursor:pointer; 옵션을 넣어주면 더 좋을것 같아요! 
3. 헤더 타이틀 넣으면 좋을 것 같아요!

**Comment by bangsk2** [comment]
피드백 감사합니다!
1. 랭킹 시스템 도입에 대해서 고려해보도록 하겠습니다!
2. 커서 옵션에 대해서도 추후 반영하도록 고려해보겠습니다!
3. 헤더 타이틀을 도입하여 홈페이지 새로고침 등 옵션을 적용할 수 있도록 개선해보겠습니다!


피드백 감사합니다!
