### ISSUE TITLE
[피드백] 멋있는 야구 게임이 될 거 같아요!

### ISSUE THREAD

**Issue by cbj0010** [woorifisa-service-dev-3rd/frontend-1st-Number_Baseball#17]
1. 나중에 마우스만 가지고 게임할 경우, 숫자를 입력했을 때 쉽게 지울 수 있도록 삭제 버튼이 있으면 좋을 것 같습니다!
2. 숫자야구 게임을 다른 사람과 함께 플레이 하여 먼저 맞출 수 있도록 하는 기능도 추가 되면 재밌을 것 같습니다!
3. numberBase Ball이미지가 위아래로 좀 찌그러져있는거 같아요..ㅠㅜ ㅎㅎ...

**Comment by bangsk2** [comment]
1. 추후 입력버튼 추가와 함께 넣을 수 있도록 하겠습니다!
2. 확인해보고 추후에 커스텀 게임 방안을 도입해보도록 하겠습니다. 좋은 의견 감사합니다.
3. 전체적인 UI 수정에서 해당사항을 반영할 수 있도록 하겠습니다!

피드백 감사합니다!
