### ISSUE TITLE
triple-roulette-review

### ISSUE THREAD

**Issue by qbobl5** [woorifisa-service-dev-3rd/frontend-1st-Number_Baseball#18]
숫자를 모두 작성하고 따로 제출할 수 있는 버튼이 있으면 더 좋을 것 같아요.
그리고 로고 조금만 더 위아래로 길면 귀여울 것 같습니다. ^__^

**Comment by bangsk2** [comment]
피드백 감사합니다! 
해당 부분을 반영하여 UI 수정을 하고 제출버튼과 함께 지우기 버튼도 도입할 수 있도록 수정하겠습니다!
