### ISSUE TITLE
UI 개선이 필요할 듯 합니다!

### ISSUE THREAD

**Issue by gusdk19** [woorifisa-service-dev-3rd/frontend-1st-Number_Baseball#19]
예전 야후 게임..이 생각나는 UI가 조금 아쉬웠습니다.
상단 배너가 눌린 느낌이 조금 나는 것 같아요..!

input에 음수나 두 자리 수 이상이 들어가지 않도록 수정이 필요할 것 같습니다.

**Comment by bangsk2** [comment]
피드백 감사합니다!
UI부분은 차후에 수정할 수 있도록 하겠습니다!

피드백주신 input 부분 또한 추후에 수정하여 원활한 게임을 운용할 수 있도록 하겠습니다!
